//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SRS_libraryModel", "FK_tbluser_tblroles", "tblroles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SRS_libraryModel.tblrole), "tbluser", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SRS_libraryModel.tbluser), true)]

#endregion

namespace SRS_libraryModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SRS_libraryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SRS_libraryEntities object using the connection string found in the 'SRS_libraryEntities' section of the application configuration file.
        /// </summary>
        public SRS_libraryEntities() : base("name=SRS_libraryEntities", "SRS_libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SRS_libraryEntities object.
        /// </summary>
        public SRS_libraryEntities(string connectionString) : base(connectionString, "SRS_libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SRS_libraryEntities object.
        /// </summary>
        public SRS_libraryEntities(EntityConnection connection) : base(connection, "SRS_libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Add_Book> Add_Book
        {
            get
            {
                if ((_Add_Book == null))
                {
                    _Add_Book = base.CreateObjectSet<Add_Book>("Add_Book");
                }
                return _Add_Book;
            }
        }
        private ObjectSet<Add_Book> _Add_Book;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Add_Reader> Add_Reader
        {
            get
            {
                if ((_Add_Reader == null))
                {
                    _Add_Reader = base.CreateObjectSet<Add_Reader>("Add_Reader");
                }
                return _Add_Reader;
            }
        }
        private ObjectSet<Add_Reader> _Add_Reader;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblrole> tblroles
        {
            get
            {
                if ((_tblroles == null))
                {
                    _tblroles = base.CreateObjectSet<tblrole>("tblroles");
                }
                return _tblroles;
            }
        }
        private ObjectSet<tblrole> _tblroles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbluser> tblusers
        {
            get
            {
                if ((_tblusers == null))
                {
                    _tblusers = base.CreateObjectSet<tbluser>("tblusers");
                }
                return _tblusers;
            }
        }
        private ObjectSet<tbluser> _tblusers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Add_Book EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdd_Book(Add_Book add_Book)
        {
            base.AddObject("Add_Book", add_Book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Add_Reader EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdd_Reader(Add_Reader add_Reader)
        {
            base.AddObject("Add_Reader", add_Reader);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblroles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblroles(tblrole tblrole)
        {
            base.AddObject("tblroles", tblrole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblusers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblusers(tbluser tbluser)
        {
            base.AddObject("tblusers", tbluser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SRS_libraryModel", Name="Add_Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Add_Book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Add_Book object.
        /// </summary>
        /// <param name="book_id">Initial value of the Book_id property.</param>
        public static Add_Book CreateAdd_Book(global::System.Int32 book_id)
        {
            Add_Book add_Book = new Add_Book();
            add_Book.Book_id = book_id;
            return add_Book;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Book_id
        {
            get
            {
                return _Book_id;
            }
            set
            {
                if (_Book_id != value)
                {
                    OnBook_idChanging(value);
                    ReportPropertyChanging("Book_id");
                    _Book_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Book_id");
                    OnBook_idChanged();
                }
            }
        }
        private global::System.Int32 _Book_id;
        partial void OnBook_idChanging(global::System.Int32 value);
        partial void OnBook_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Name
        {
            get
            {
                return _Book_Name;
            }
            set
            {
                OnBook_NameChanging(value);
                ReportPropertyChanging("Book_Name");
                _Book_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Name");
                OnBook_NameChanged();
            }
        }
        private global::System.String _Book_Name;
        partial void OnBook_NameChanging(global::System.String value);
        partial void OnBook_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Author_Name
        {
            get
            {
                return _Book_Author_Name;
            }
            set
            {
                OnBook_Author_NameChanging(value);
                ReportPropertyChanging("Book_Author_Name");
                _Book_Author_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Author_Name");
                OnBook_Author_NameChanged();
            }
        }
        private global::System.String _Book_Author_Name;
        partial void OnBook_Author_NameChanging(global::System.String value);
        partial void OnBook_Author_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_ISBN
        {
            get
            {
                return _Book_ISBN;
            }
            set
            {
                OnBook_ISBNChanging(value);
                ReportPropertyChanging("Book_ISBN");
                _Book_ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_ISBN");
                OnBook_ISBNChanged();
            }
        }
        private global::System.String _Book_ISBN;
        partial void OnBook_ISBNChanging(global::System.String value);
        partial void OnBook_ISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Publisher_name
        {
            get
            {
                return _Book_Publisher_name;
            }
            set
            {
                OnBook_Publisher_nameChanging(value);
                ReportPropertyChanging("Book_Publisher_name");
                _Book_Publisher_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Publisher_name");
                OnBook_Publisher_nameChanged();
            }
        }
        private global::System.String _Book_Publisher_name;
        partial void OnBook_Publisher_nameChanging(global::System.String value);
        partial void OnBook_Publisher_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Book_Publication_date
        {
            get
            {
                return _Book_Publication_date;
            }
            set
            {
                OnBook_Publication_dateChanging(value);
                ReportPropertyChanging("Book_Publication_date");
                _Book_Publication_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Book_Publication_date");
                OnBook_Publication_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Book_Publication_date;
        partial void OnBook_Publication_dateChanging(Nullable<global::System.DateTime> value);
        partial void OnBook_Publication_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Book_Price
        {
            get
            {
                return _Book_Price;
            }
            set
            {
                OnBook_PriceChanging(value);
                ReportPropertyChanging("Book_Price");
                _Book_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Book_Price");
                OnBook_PriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Book_Price;
        partial void OnBook_PriceChanging(Nullable<global::System.Int32> value);
        partial void OnBook_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Book_Quantity
        {
            get
            {
                return _Book_Quantity;
            }
            set
            {
                OnBook_QuantityChanging(value);
                ReportPropertyChanging("Book_Quantity");
                _Book_Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Book_Quantity");
                OnBook_QuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Book_Quantity;
        partial void OnBook_QuantityChanging(Nullable<global::System.Int32> value);
        partial void OnBook_QuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Branch
        {
            get
            {
                return _Book_Branch;
            }
            set
            {
                OnBook_BranchChanging(value);
                ReportPropertyChanging("Book_Branch");
                _Book_Branch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Branch");
                OnBook_BranchChanged();
            }
        }
        private global::System.String _Book_Branch;
        partial void OnBook_BranchChanging(global::System.String value);
        partial void OnBook_BranchChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SRS_libraryModel", Name="Add_Reader")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Add_Reader : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Add_Reader object.
        /// </summary>
        /// <param name="reader_id">Initial value of the Reader_id property.</param>
        public static Add_Reader CreateAdd_Reader(global::System.Int32 reader_id)
        {
            Add_Reader add_Reader = new Add_Reader();
            add_Reader.Reader_id = reader_id;
            return add_Reader;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Reader_id
        {
            get
            {
                return _Reader_id;
            }
            set
            {
                if (_Reader_id != value)
                {
                    OnReader_idChanging(value);
                    ReportPropertyChanging("Reader_id");
                    _Reader_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Reader_id");
                    OnReader_idChanged();
                }
            }
        }
        private global::System.Int32 _Reader_id;
        partial void OnReader_idChanging(global::System.Int32 value);
        partial void OnReader_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reader_Studentid
        {
            get
            {
                return _Reader_Studentid;
            }
            set
            {
                OnReader_StudentidChanging(value);
                ReportPropertyChanging("Reader_Studentid");
                _Reader_Studentid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reader_Studentid");
                OnReader_StudentidChanged();
            }
        }
        private global::System.String _Reader_Studentid;
        partial void OnReader_StudentidChanging(global::System.String value);
        partial void OnReader_StudentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reader_Name
        {
            get
            {
                return _Reader_Name;
            }
            set
            {
                OnReader_NameChanging(value);
                ReportPropertyChanging("Reader_Name");
                _Reader_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reader_Name");
                OnReader_NameChanged();
            }
        }
        private global::System.String _Reader_Name;
        partial void OnReader_NameChanging(global::System.String value);
        partial void OnReader_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reader_Address
        {
            get
            {
                return _Reader_Address;
            }
            set
            {
                OnReader_AddressChanging(value);
                ReportPropertyChanging("Reader_Address");
                _Reader_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reader_Address");
                OnReader_AddressChanged();
            }
        }
        private global::System.String _Reader_Address;
        partial void OnReader_AddressChanging(global::System.String value);
        partial void OnReader_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reader_Phone
        {
            get
            {
                return _Reader_Phone;
            }
            set
            {
                OnReader_PhoneChanging(value);
                ReportPropertyChanging("Reader_Phone");
                _Reader_Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reader_Phone");
                OnReader_PhoneChanged();
            }
        }
        private global::System.String _Reader_Phone;
        partial void OnReader_PhoneChanging(global::System.String value);
        partial void OnReader_PhoneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SRS_libraryModel", Name="tblrole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblrole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblrole object.
        /// </summary>
        /// <param name="roleId">Initial value of the roleId property.</param>
        /// <param name="rolename">Initial value of the rolename property.</param>
        public static tblrole Createtblrole(global::System.Int32 roleId, global::System.String rolename)
        {
            tblrole tblrole = new tblrole();
            tblrole.roleId = roleId;
            tblrole.rolename = rolename;
            return tblrole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleId
        {
            get
            {
                return _roleId;
            }
            set
            {
                if (_roleId != value)
                {
                    OnroleIdChanging(value);
                    ReportPropertyChanging("roleId");
                    _roleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("roleId");
                    OnroleIdChanged();
                }
            }
        }
        private global::System.Int32 _roleId;
        partial void OnroleIdChanging(global::System.Int32 value);
        partial void OnroleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rolename
        {
            get
            {
                return _rolename;
            }
            set
            {
                OnrolenameChanging(value);
                ReportPropertyChanging("rolename");
                _rolename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rolename");
                OnrolenameChanged();
            }
        }
        private global::System.String _rolename;
        partial void OnrolenameChanging(global::System.String value);
        partial void OnrolenameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SRS_libraryModel", "FK_tbluser_tblroles", "tbluser")]
        public EntityCollection<tbluser> tblusers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbluser>("SRS_libraryModel.FK_tbluser_tblroles", "tbluser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbluser>("SRS_libraryModel.FK_tbluser_tblroles", "tbluser", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SRS_libraryModel", Name="tbluser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbluser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbluser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="roleid">Initial value of the roleid property.</param>
        public static tbluser Createtbluser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Int32 roleid)
        {
            tbluser tbluser = new tbluser();
            tbluser.Id = id;
            tbluser.username = username;
            tbluser.password = password;
            tbluser.roleid = roleid;
            return tbluser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleid
        {
            get
            {
                return _roleid;
            }
            set
            {
                OnroleidChanging(value);
                ReportPropertyChanging("roleid");
                _roleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleid");
                OnroleidChanged();
            }
        }
        private global::System.Int32 _roleid;
        partial void OnroleidChanging(global::System.Int32 value);
        partial void OnroleidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SRS_libraryModel", "FK_tbluser_tblroles", "tblroles")]
        public tblrole tblrole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblrole>("SRS_libraryModel.FK_tbluser_tblroles", "tblroles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblrole>("SRS_libraryModel.FK_tbluser_tblroles", "tblroles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblrole> tblroleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblrole>("SRS_libraryModel.FK_tbluser_tblroles", "tblroles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblrole>("SRS_libraryModel.FK_tbluser_tblroles", "tblroles", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
